version: '3.8'
services:
  anythingllm:
    image: mintplexlabs/anythingllm
    container_name: anythingllm
    ports:
    - "3001"
    cap_add:
      - SYS_ADMIN
    networks:
      - internal
      - proxy
    environment:
    # Adjust for your environment
      - STORAGE_DIR=/app/server/storage
      - JWT_SECRET="1d4bbf9965d9d3ec0853f3c9a4039b17bdd6bf88c4c24e5f13ee26899051"
      - LLM_PROVIDER=ollama
      - OLLAMA_BASE_PATH=http://ollama:11434
      - OLLAMA_MODEL_PREF=gemma3:27b
      - OLLAMA_MODEL_TOKEN_LIMIT=128000
      - EMBEDDING_ENGINE=ollama
      - EMBEDDING_BASE_PATH=http://ollama:11434
      - EMBEDDING_MODEL_PREF=nomic-embed-text:latest
      - EMBEDDING_MODEL_MAX_CHUNK_LENGTH=8192
      - VECTOR_DB=lancedb
      - WHISPER_PROVIDER=local
      - TTS_PROVIDER=native
      - PASSWORDMINCHAR=8
      # Add any other keys here for services or settings
      # you can find in the docker/.env.example file
    volumes:
      - anythingllm:/app/server/storage
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy

      - traefik.http.routers.anythingllm.rule=Host(`anythingllm.${DOMAIN_NAME}`)
      - traefik.http.routers.anythingllm.entrypoints=websecure
      - traefik.http.routers.anythingllm.service=anythingllm
      - traefik.http.routers.anythingllm.tls=true
      - traefik.http.routers.anythingllm.tls.certresolver=letsencrypt

      - traefik.http.services.anythingllm.loadbalancer.server.port=3001
    restart: always

volumes:
  anythingllm:

networks:
  internal:
    name: internal
    external: true

  proxy:
    name: proxy
    external: true
