version: '3.9'
name: media-stack
services:
  transmission:
    container_name: transmission
    image: linuxserver/transmission:4.0.6
    networks:
      - media-stack
      - proxy
    ports:
      - 51413:51413
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - USER=admin
      - PASS=torrenteer
    volumes:
      - downloads:/downloads
      - tx-config:/config
      - tx-watch:/watch
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.transmission.rule=Host(`transmission.${DOMAIN_NAME}`)
      - traefik.http.routers.transmission.entrypoints=websecure
      - traefik.http.routers.transmission.service=transmission
      - traefik.http.routers.transmission.tls=true
      - traefik.http.routers.transmission.tls.certresolver=letsencrypt
      - traefik.http.services.transmission.loadbalancer.server.port=9091

  sonarr:
    image: linuxserver/sonarr:4.0.15-develop
    container_name: sonarr
    networks:
      - media-stack
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - sonarr-config:/config
      - downloads:/downloads
    # ports:
    #   - 8989
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.sonarr.rule=Host(`sonarr.${DOMAIN_NAME}`)
      - traefik.http.routers.sonarr.entrypoints=websecure
      - traefik.http.routers.sonarr.service=sonarr
      - traefik.http.routers.sonarr.tls=true
      - traefik.http.routers.sonarr.tls.certresolver=letsencrypt
      - traefik.http.services.sonarr.loadbalancer.server.port=8989

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:5.27.5
    networks:
      - media-stack
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    # ports:
    #   - 7878
    volumes:
      - radarr-config:/config
      - downloads:/downloads
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.radarr.rule=Host(`radarr.${DOMAIN_NAME}`)
      - traefik.http.routers.radarr.entrypoints=websecure
      - traefik.http.routers.radarr.service=radarr
      - traefik.http.routers.radarr.tls=true
      - traefik.http.routers.radarr.tls.certresolver=letsencrypt
      - traefik.http.services.radarr.loadbalancer.server.port=7878

  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:2.0.5
    networks:
      - media-stack
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - prowlarr-config:/config
    # ports:
    #   - 9696
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.prowlarr.rule=Host(`prowlarr.${DOMAIN_NAME}`)
      - traefik.http.routers.prowlarr.entrypoints=websecure
      - traefik.http.routers.prowlarr.service=prowlarr
      - traefik.http.routers.prowlarr.tls=true
      - traefik.http.routers.prowlarr.tls.certresolver=letsencrypt
      - traefik.http.services.prowlarr.loadbalancer.server.port=9696

  jellyfin:
    image: linuxserver/jellyfin:10.10.7
    container_name: jellyfin
    networks:
      - media-stack
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - jellyfin-config:/config
      - downloads:/data
    # devices:
    #  - /dev/videoN:/dev/videoN # Mount GPU device 
    ports:
      # - 8096 # http
      # - 8920 # https
      - 7359:7359/udp # discovery
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy

      - traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAIN_NAME}`)
      - traefik.http.routers.jellyfin.entrypoints=websecure
      - traefik.http.routers.jellyfin.service=jellyfin
      - traefik.http.routers.jellyfin.tls=true
      - traefik.http.routers.jellyfin.tls.certresolver=letsencrypt

      - traefik.http.routers.jellyfin-pub.rule=Host(`movies.${PUB_DOMAIN_NAME}`)
      - traefik.http.routers.jellyfin-pub.entrypoints=pubsecure
      - traefik.http.routers.jellyfin-pub.service=jellyfin
      - traefik.http.routers.jellyfin-pub.tls=true
      - traefik.http.routers.jellyfin-pub.tls.certresolver=letsencrypt

      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
      #- traefik.http.services.jellyfin.loadbalancer.server.scheme=https

volumes:
  downloads:
  tx-config:
  tx-watch:
  sonarr-config:
  radarr-config:
  prowlarr-config:
  jellyfin-config:

networks:
  media-stack:
    internal: true
  proxy:
    name: proxy
    external: true
