version: '3.9'
name: media-stack
services:
  transmission:
    container_name: transmission
    image: linuxserver/transmission:4.0.3
    network_mode: host # use host networking here for upnp to work
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - USER=admin
      - PASS=torrenteer
    volumes:
      - downloads:/downloads
      - tx-config:/config
      - tx-watch:/watch
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.transmission.rule=Host(`transmission.${DOMAIN_NAME}`)
      - traefik.http.routers.transmission.entrypoints=websecure
      - traefik.http.routers.transmission.service=transmission
      - traefik.http.routers.transmission.tls=true
      - traefik.http.routers.transmission.tls.certresolver=letsencrypt
      - traefik.http.services.transmission.loadbalancer.server.port=9091

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:4.6.4
    networks:
      - media-stack
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    ports:
      - 7878
    volumes:
      - radarr-config:/config
      - downloads:/downloads
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.radarr.rule=Host(`radarr.${DOMAIN_NAME}`)
      - traefik.http.routers.radarr.entrypoints=websecure
      - traefik.http.routers.radarr.service=radarr
      - traefik.http.routers.radarr.tls=true
      - traefik.http.routers.radarr.tls.certresolver=letsencrypt
      - traefik.http.services.radarr.loadbalancer.server.port=7878

  jellyfin:
    image: linuxserver/jellyfin:10.8.10
    container_name: jellyfin
    networks:
      - media-stack
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - jellyfin-config:/config
      - downloads:/data
    # devices:
    #  - /dev/videoN:/dev/videoN # Mount GPU device 
    ports:
      - 8096 # http
      - 8920 # https
      - 7359:7359/udp # discovery
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.jellyfin.rule=Host(`movies.${PUB_DOMAIN_NAME}`)
      - traefik.http.routers.jellyfin.entrypoints=pubsecure
      - traefik.http.routers.jellyfin.service=jellyfin
      - traefik.http.routers.jellyfin.tls=true
      - traefik.http.routers.jellyfin.tls.certresolver=letsencrypt
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
      #- traefik.http.services.jellyfin.loadbalancer.server.scheme=https

volumes:
  downloads:
  tx-config:
  tx-watch:
  radarr-config:
  jellyfin-config:

networks:
  media-stack:
    internal: true
  proxy:
    name: proxy
    external: true
