#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
PODMAN_SECRETS=()

secret_exists() {
  podman secret inspect "$1" >/dev/null 2>&1
}

create_secret() {
  local name="$1" value="$2"
  if secret_exists "$name"; then
    note "keeping existing Podman secret: $name"
    return
  fi
  printf '%s' "$value" | podman secret create "$name" - >/dev/null
  PODMAN_SECRETS+=("$name")
  printf '  %s✓ created%s Podman secret %s\n' "$GREEN" "$RESET" "$name"
}

remove_env() {
  local key="$1" temporary
  [[ -f "$ENV_FILE" ]] || return
  temporary="$(mktemp)"
  grep -vE "^${key}=" "$ENV_FILE" >"$temporary" || true
  mv "$temporary" "$ENV_FILE"
}

ask_multiline_secret() {
  local variable="$1" line value=""
  say "$2"
  note "Paste the complete value, then enter a line containing only __END__."
  if [[ -t 0 ]]; then
    stty -echo
    trap 'stty echo' EXIT INT TERM
  fi
  while IFS= read -r line; do
    [[ "$line" == "__END__" ]] && break
    value+="${line}"$'\n'
  done
  if [[ -t 0 ]]; then
    stty echo
    trap - EXIT INT TERM
    printf '\n'
  fi
  value="${value%$'\n'}"
  printf -v "$variable" '%s' "$value"
}

command -v podman >/dev/null 2>&1 || { echo 'podman is required' >&2; exit 1; }
command -v podman-compose >/dev/null 2>&1 || { echo 'podman-compose is required' >&2; exit 1; }
command -v openssl >/dev/null 2>&1 || { echo 'openssl is required' >&2; exit 1; }
command -v jq >/dev/null 2>&1 || { echo 'jq is required' >&2; exit 1; }

banner "OpenBao Authorizer setup"

stage "Deployment values"
[[ -f "$ENV_FILE" ]] || cp .env.example "$ENV_FILE"
ask DOMAIN_NAME "Internal domain name:"
[[ -n "$DOMAIN_NAME" ]] || { echo 'DOMAIN_NAME is required' >&2; exit 1; }
ask VAPID_SUBJECT "VAPID contact (mailto: address or HTTPS URL):"
[[ "$VAPID_SUBJECT" == mailto:* || "$VAPID_SUBJECT" == https://* ]] || {
  echo 'VAPID_SUBJECT must start with mailto: or https://' >&2
  exit 1
}
write_env DOMAIN_NAME "$DOMAIN_NAME"
write_env VAPID_SUBJECT "$VAPID_SUBJECT"
remove_env APPROVER_PASSWORD
remove_env AGENT_PASSWORD
remove_env ADMIN_PASSWORD

stage "Generated core secrets"
say "Strong values will be generated locally and sent directly to Podman."
if ! secret_exists openbao_static_seal_key; then
  seal_key="$(openssl rand -base64 32 | tr -d '\n')"
  printf '%s' "$seal_key" | openssl base64 -d -A | podman secret create openbao_static_seal_key - >/dev/null
  PODMAN_SECRETS+=("openbao_static_seal_key")
  unset seal_key
  printf '  %s✓ created%s Podman secret openbao_static_seal_key\n' "$GREEN" "$RESET"
else
  note "keeping existing Podman secret: openbao_static_seal_key"
fi

if ! secret_exists authorizer_encryption_key; then
  encryption_key="$(openssl rand -base64 32 | tr -d '\n')"
  create_secret authorizer_encryption_key "$encryption_key"
  unset encryption_key
fi

for password_secret in admin_password approver_password agent_password; do
  if ! secret_exists "$password_secret"; then
    create_secret "$password_secret" "$(openssl rand -base64 32 | tr -d '\n')"
  fi
done

if ! secret_exists openbao_scanner_token; then
  create_secret openbao_scanner_token "pending-initial-setup"
fi

stage "GitHub App"
say "Create a private GitHub App that issues installation tokens; no webhook or callback is needed."
open_url "https://github.com/settings/apps/new"
step "Choose the owning account, enter a unique app name, and use https://baoauthz.${DOMAIN_NAME} as the homepage URL."
step "Disable the webhook. Grant the repository permissions required by permission-sets.json, using the least privilege acceptable for your workflows."
step "Create the app, copy its numeric App ID, then generate and download one private key."
ask GITHUB_APP_ID "GitHub App ID:"
[[ "$GITHUB_APP_ID" =~ ^[0-9]+$ ]] || { echo 'GitHub App ID must be numeric' >&2; exit 1; }
write_env GITHUB_APP_ID "$GITHUB_APP_ID"
if secret_exists github_app_private_key; then
  note "keeping existing Podman secret: github_app_private_key"
else
  ask_multiline_secret github_private_key "Paste the downloaded GitHub App PEM private key."
  [[ "$github_private_key" == *"BEGIN"*"PRIVATE KEY"* ]] || { echo 'value does not look like a PEM private key' >&2; exit 1; }
  create_secret github_app_private_key "$github_private_key"
fi
step "Install the app on each account listed in permission-sets.json and grant its selected repositories."
step "Copy each installation ID from GitHub and update the matching installation_id values in permission-sets.json."
pause "Press Enter after verifying the installations and IDs."

stage "Web Push VAPID keys"
say "VAPID keys are generated by this server, not issued by Mozilla."
say "Firefox chooses Mozilla's push endpoint when a browser subscribes over HTTPS."
if secret_exists vapid_public_key && secret_exists vapid_private_key; then
  note "keeping existing Podman VAPID secrets"
elif secret_exists vapid_public_key || secret_exists vapid_private_key; then
  echo 'only one VAPID secret exists; remove both vapid_public_key and vapid_private_key, then rerun the wizard' >&2
  exit 1
else
  say "Generating a P-256 VAPID pair with web-push@3.6.7 in a disposable Node container."
  vapid_json="$(podman run --rm docker.io/library/node:24-alpine npx --yes web-push@3.6.7 generate-vapid-keys --json)"
  vapid_public_key="$(printf '%s' "$vapid_json" | jq -er '.publicKey')"
  vapid_private_key="$(printf '%s' "$vapid_json" | jq -er '.privateKey')"
  create_secret vapid_public_key "$vapid_public_key"
  create_secret vapid_private_key "$vapid_private_key"
  unset vapid_json vapid_public_key vapid_private_key
fi
note "Mozilla Push is already allowed by authorizer.hcl via updates.push.services.mozilla.com."
note "Fennec UnifiedPush may instead use ntfy.sh, which is also allowed."

stage "Verify Podman secrets"
for secret in openbao_static_seal_key authorizer_encryption_key admin_password approver_password agent_password github_app_private_key vapid_public_key vapid_private_key openbao_scanner_token; do
  if secret_exists "$secret"; then
    printf '  %s✓ found%s %s\n' "$GREEN" "$RESET" "$secret"
  else
    echo "missing Podman secret: $secret" >&2
    exit 1
  fi
done
note "make setup replaces the openbao_scanner_token placeholder with an issued token."
note "Retrieve a login password only when needed with:"
note "podman secret inspect --showsecret --format '{{.SecretData}}' admin_password"

stage "Next steps"
say "Deploy and initialize OpenBao in this order:"
step "make deploy"
step "make initialize"
step "make setup"
step "make start"

finish
(( ${#PODMAN_SECRETS[@]} )) && note "created Podman secrets: ${PODMAN_SECRETS[*]}"
true
