version: '3.7'

services:
  tabby:
    restart: always
    image: tabbyml/tabby:0.24.0-rc.0
    command: serve --model TabbyML/DeepseekCoder-6.7B --device cuda --webserver
    volumes:
      - tabby:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy

      # - traefik.http.routers.tabby.rule=Host(`tabby.${DOMAIN_NAME}`)
      # - traefik.http.routers.tabby.entrypoints=websecure
      # - traefik.http.routers.tabby.service=tabby
      # - traefik.http.routers.tabby.tls=true
      # - traefik.http.routers.tabby.tls.certresolver=letsencrypt

      - traefik.http.routers.tabby-pub.rule=Host(`tabby.${PUB_DOMAIN_NAME}`)
      - traefik.http.routers.tabby-pub.entrypoints=pubsecure
      - traefik.http.routers.tabby-pub.service=tabby
      - traefik.http.routers.tabby-pub.tls=true
      - traefik.http.routers.tabby-pub.tls.certresolver=letsencrypt

      - traefik.http.services.tabby.loadbalancer.server.port=8080
    networks:
      - proxy

networks:
  proxy:
    name: proxy
    external: true

volumes:
  tabby:
